apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/restartedAt: "2023-09-10T09:34:58-04:00"
    kubernetes.io/psp: eks.privileged
  creationTimestamp: "2023-09-10T13:34:58Z"
  generateName: arsms-847d5c8cc7-
  labels:
    pod-template-hash: 847d5c8cc7
    run: arsms
  name: arsms-847d5c8cc7-vpq9q
  namespace: prod
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: arsms-847d5c8cc7
    uid: aee3b800-cc51-4fe3-8663-2af7919f77d3
  resourceVersion: "177367098"
  uid: 93b64e9d-0458-4e1e-9077-1aa3a3739e0b
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: run
              operator: In
              values:
              - arsms
          topologyKey: kubernetes.io/hostname
        weight: 100
  containers:
  - env:
    - name: DD_AGENT_HOST
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.hostIP
    - name: DD_SERVICE_NAME
      value: arsms
    - name: DD_TRACE_SPAN_TAGS
      value: env:cec-prod-eks
    - name: DD_TRACE_AGENT_PORT
      value: "8126"
    - name: eureka_instance_hostname
      value: arsms
    - name: eureka_client_serviceUrl_defaultZone
      value: http://registry:8761/eureka/
    - name: SPRING_PROFILES_ACTIVE
      value: DEFAULT
    - name: ELASTIC_APM_SERVICE_NAME
      value: arsms
    - name: ELASTIC_APM_SECRET_TOKEN
      valueFrom:
        secretKeyRef:
          key: ELASTIC_APM_SECRET_TOKEN
          name: secret-sa-observability
    - name: JAVA_TOOL_OPTIONS
      value: -javaagent:/opt/apm/agent/elastic-apm-agent.jar
    image: 854587915883.dkr.ecr.us-east-1.amazonaws.com/arsms:v6.0.0-1315544805-release-2020-1-1-1
    imagePullPolicy: Always
    livenessProbe:
      failureThreshold: 2
      httpGet:
        path: /actuator/info
        port: 8787
        scheme: HTTP
      initialDelaySeconds: 400
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 2
    name: arsms
    ports:
    - containerPort: 8787
      protocol: TCP
    readinessProbe:
      failureThreshold: 2
      httpGet:
        path: /actuator/info
        port: 8787
        scheme: HTTP
      initialDelaySeconds: 400
      periodSeconds: 10
      successThreshold: 4
      timeoutSeconds: 2
    resources:
      limits:
        cpu: 650m
        memory: 1024M
      requests:
        cpu: 400m
        memory: 1024M
    terminationMessagePath: /default/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /opt/apm/agent
      name: efs-apm-agent-pvc
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-tvj5w
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: us-west-2-ecr-registry
  nodeName: ip-100-67-8-217.us-west-2.compute.internal
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  topologySpreadConstraints:
  - labelSelector:
      matchLabels:
        run: arsms
    maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: ScheduleAnyway
  volumes:
  - name: efs-apm-agent-pvc
    persistentVolumeClaim:
      claimName: efs-apm-agent-pvc
  - name: kube-api-access-tvj5w
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-09-10T13:34:58Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-09-10T13:49:47Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-09-10T13:49:47Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-09-10T13:34:58Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://a13f2284221b5bbf226602c903f04bd4258cc8da0d6b28d0964b3006826b7578
    image: 854587915883.dkr.ecr.us-east-1.amazonaws.com/arsms:v6.0.0-1315544805-release-2020-1-1-1
    imageID: docker-pullable://854587915883.dkr.ecr.us-east-1.amazonaws.com/arsms@sha256:3586ccb76d7a36632c13d933757bfad52d2dcbeedd86e000911a9ecb22a0c0a6
    lastState:
      terminated:
        containerID: docker://5a2114919f0cd36548a2f95823458a516403d97a5764a88d777ad1a1e93e8ddc
        exitCode: 137
        finishedAt: "2023-09-10T13:42:21Z"
        reason: Error
        startedAt: "2023-09-10T13:35:01Z"
    name: arsms
    ready: true
    restartCount: 1
    started: true
    state:
      running:
        startedAt: "2023-09-10T13:42:22Z"
  hostIP: 100.67.8.217
  phase: Running
  podIP: 100.67.8.144
  podIPs:
  - ip: 100.67.8.144
  qosClass: Burstable
  startTime: "2023-09-10T13:34:58Z"
