apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/restartedAt: "2024-04-29T07:06:14Z"
  creationTimestamp: "2024-04-29T07:06:14Z"
  generateName: ecm-799f4c7dd9-
  labels:
    app.kubernetes.io/name: ecm
    pod-template-hash: 799f4c7dd9
  name: ecm-799f4c7dd9-s9rk6
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: ecm-799f4c7dd9
    uid: 80725a22-b467-46db-95eb-4333f0f90fd7
  resourceVersion: "88995434"
  uid: 7345e876-8811-49e3-a31c-f4f95b7a7841
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: ecm
          topologyKey: kubernetes.io/hostname
        weight: 1
  containers:
  - args:
    - /init/ecm-start.sh
    command:
    - /bin/bash
    env:
    - name: FEATURE_TASKRUNNER_ENABLED
      value: "false"
    - name: UMASK
      value: "0022"
    - name: FQDN
      value: sji-prod-migrate.saviyntcloud.com
    - name: CYBER_SAFE_TRUST_BROKER_FILE
      value: cstb
    - name: IS_RUNNING_IN_K8S
      value: "true"
    - name: GIT_BASE_FOLDER
      value: /application_instance/custom_code/
    - name: BOUNCER_URL
      value: http://bouncer:3000
    - name: ECM_RESTART_URL
      value: http://bouncer:3000/reset_ecm
    - name: AUTHMS_RESTART_URL
      value: http://bouncer:3000/reset_authms
    - name: ECM_WORKER_REPLICA_COUNT_URL
      value: http://bouncer:3000/deployment/ecm-worker/status
    - name: DISABLE_JOBS
      value: "true"
    - name: JAVA_OPTS
      value: -Xms2000m -Xmx8000m -Xverify:none -Djavax.net.ssl.trustStore=/saviynt_shared/saviynt/security/cacerts
        -Djavax.net.ssl.trustStorePassword=changeit  -XX:+HeapDumpOnOutOfMemoryError
        -XX:HeapDumpPath=/saviynt_shared/ecm_dumps/ecm-ui.bin
    - name: SHARED_BASE_FOLDER
      value: /saviynt_shared
    - name: SHARED_CERT_FOLDER
      value: /saviynt_shared_certs
    - name: CAPTCHA_KEY
    - name: CAPTCHA_SECRET
    - name: CATALINA_OUT
      value: /dev/stdout
    - name: CONTENT_BASS_URI_SRC
    - name: CONTENT_CONNECT_SRC
    - name: CONTENT_DEFAULT_SRC
    - name: CONTENT_FONT_SRC
    - name: CONTENT_FRAME_SRC
    - name: CONTENT_IMAGE_SRC
    - name: CONTENT_MANIFEST_SRC
    - name: CONTENT_MEDIA_SRC
    - name: CONTENT_OBJECT_SRC
    - name: CONTENT_PREFETCH_SRC
    - name: CONTENT_SCRIPT_SRC
      value: '''unsafe-inline'' ''unsafe-eval'''
    - name: CONTENT_STYLE_SRC
      value: '''unsafe-inline'''
    - name: CSFC5CCNAME
      value: MEMORY:SIGA
    - name: CSFC5ROOTPATH
      value: /saviynt_shared/cstb
    - name: ELASTICSEARCH_HOSTNAME
      value: vpc-sjiprodeices-agqihco5z3iez3lvgbxxgwm3rm.us-east-1.es.amazonaws.com
    - name: ELASTICSEARCH_ISAWSES
      value: "TRUE"
    - name: ELASTICSEARCH_PORT
      value: "443"
    - name: ELASTICSEARCH_PROTOCOL
      value: https
    - name: ELASTICSEARCH_REGION
      value: us-east-1
    - name: ELASTICSEARCH_SERVICENAME
      value: es
    - name: ELASTICSEARCH_USERNAME
      value: na
    - name: ENABLE_SAML_LOG
      value: "false"
    - name: ENABLE_SYSOUT_IN_ECM_LOGS
      value: "false"
    - name: FEATURE_HTTPONLY_ACCESSTOKEN
      value: "false"
    - name: FEATURE_USE_AUTHMS
      value: "false"
    - name: GRAILS_PLUGIN_SPRINGSECURITY_DAO_REFLECTIONSALTSOURCEPROPERTY
      value: missing
    - name: GRAILS_PLUGIN_SPRINGSECURITY_PASSWORD_ALGORITHM
      value: missing
    - name: GRAILS_PLUGIN_SPRINGSECURITY_PASSWORD_HASH_ITERATIONS
      value: missingg
    - name: GRAILS_PLUGIN_SPRINGSECURITY_REST_TOKEN_STORAGE_JWT_EXPIRATION
      value: "3600"
    - name: GRAILS_PLUGIN_SPRINGSECURITY_SALT_ITERATIONS
      value: missing
    - name: HEAP_DUMP_PATH
      value: /saviynt_shared/ecm_dumps
    - name: IS_FULL_PATH_FOR_SSO_CONFIG
      value: "false"
    - name: LOGGING_PATTERN_CONSOLE
      value: "%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}} %5p [%X] ${PID:-
        } --- [%t] %logger{39} : %replace(%m%wEx{6}){'[\r\n]+', '|'}%nopex \n"
    - name: MYSQL_SSMDAU_USER
      value: ssmdau
    - name: MYSQL_SSMINLP_SCHEMA
      value: ssminlp
    - name: ORG_QUARTZ_THREADPOOL_THREADCOUNT
      value: "10"
    - name: PASSWORD_HASH
      value: bcrypt
    - name: RABBITMQ_HOST
      value: saviynt-rabbitmq
    - name: RABBITMQ_PORT
      value: "5672"
    - name: RABBITMQ_USERNAME
      value: user
    - name: SAML_PASSWORDS
      value: saviyntsp~saviynt123
    - name: SAML_STORE_PASS
      value: saviynt123
    - name: SPRING_REDIS_HOST
      value: redis
    - name: SPRING_REDIS_PORT
      value: "6379"
    - name: STORE_ECM_SESSION_IN_REDIS
      value: "false"
    - name: VIRUS_SCAN_API_URL
      valueFrom:
        secretKeyRef:
          key: api-url
          name: virus-scan-creds
    - name: VIRUS_SCAN_API_USERNAME
      valueFrom:
        secretKeyRef:
          key: username
          name: virus-scan-creds
    - name: VIRUS_SCAN_API_PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: virus-scan-creds
    - name: IMAGE_TAG
      value: Release-24.4.2
    - name: DATADOG_APM_APIKEY
      valueFrom:
        secretKeyRef:
          key: api-key
          name: datadog
    - name: DATADOG_APM_APPKEY
      valueFrom:
        secretKeyRef:
          key: app-key
          name: datadog-appkey
    - name: DATADOG_APM_CLUSTERTOKEN
      valueFrom:
        secretKeyRef:
          key: token
          name: datadog-cluster-agent
    - name: ELASTICSEARCH_AWSACCESSKEY
      valueFrom:
        secretKeyRef:
          key: elastic-aws-access-key
          name: saviynt-secrets
    - name: ELASTICSEARCH_AWSSECRETKEY
      valueFrom:
        secretKeyRef:
          key: elastic-aws-secret-key
          name: saviynt-secrets
    - name: ELASTICSEARCH_PASSWORD
      valueFrom:
        secretKeyRef:
          key: elastic-password
          name: saviynt-secrets
    - name: GRAILS_PLUGIN_SPRINGSECURITY_REST_TOKEN_STORAGE_JWT_SECRET
      valueFrom:
        secretKeyRef:
          key: jwt-secret
          name: saviynt-secrets
    - name: MYSQL_PASSWORD_ENC
      valueFrom:
        secretKeyRef:
          key: mysql-root-password
          name: saviynt-mysql-enc
    - name: MYSQL_SSMDAU_PASSWORD
      valueFrom:
        secretKeyRef:
          key: mysql-ssmdau-password
          name: saviynt-secrets
    - name: RABBITMQ_PASSWORD
      valueFrom:
        secretKeyRef:
          key: rabbitmq-password
          name: saviynt-secrets
    - name: SAML_KEYSTORE_PASSWORD
      valueFrom:
        secretKeyRef:
          key: saml-keystore-password
          name: saviynt-saml-keystore
    - name: SAVIYNT_ENCRYPTION_KEY
      valueFrom:
        secretKeyRef:
          key: value
          name: saviynt-encryption-key
    - name: SAVIYNT_SX_TOKEN
      valueFrom:
        secretKeyRef:
          key: saviynt-exchange-token
          name: saviynt-exchange
    - name: SAVIYNT_SX_URL
      valueFrom:
        secretKeyRef:
          key: saviynt-exchange-url
          name: saviynt-exchange
    - name: SAVIYNT_SX_USERNAME
      valueFrom:
        secretKeyRef:
          key: saviynt-exchange-username
          name: saviynt-exchange
    - name: ECM_URL
      value: http://ecm:8080/ECM
    - name: GATEWAY_URL
      value: http://gateway:8765/ECMv6/api
    - name: ARSMS_URL
      value: http://gateway:8765/ECMv6/api/ars
    - name: CONNECTORMS_URL
      value: http://gateway:8765/ECMv6/api/connectorms
    - name: IDWMS_URL
      value: http://gateway:8765/ECMv6/api/idw
    - name: LOGMS_URL
      value: http://gateway:8765/ECMv6/api/logms
    - name: PAMMS_URL
      value: http://gateway:8765/ECMv6/api/pam
    - name: RDPGATEWAY_URL
      value: http://gateway:8765/ECMv6/api/rdpgateway
    - name: SSHGATEWAY_URL
      value: http://gateway:8765/ECMv6/api/sshgateway
    - name: TASKRUNNERMS_URL
      value: http://taskrunnerms-service.isolated-taskrunner.svc.cluster.local:8080
    - name: USERMS_URL
      value: http://gateway:8765/ECMv6/api/userms
    - name: PROMETHEUS_EXPORTER_ENABLED
      value: "true"
    - name: PROMETHEUS_EXPORTER_PORT
      value: "7070"
    - name: PROMETHEUS_EXPORTER_JAR_PATH
      value: /prometheus-exporter/jmx_prometheus_javaagent-0.16.1.jar
    - name: PROMETHEUS_EXPORTER_CONFIG_PATH
      value: /prometheus-exporter/jmx_prometheus_javaagent_config.yaml
    image: 661222050851.dkr.ecr.us-east-1.amazonaws.com/ecm:Release-24.4.2
    imagePullPolicy: Always
    livenessProbe:
      failureThreshold: 30
      httpGet:
        httpHeaders:
        - name: Host
          value: sji-prod-migrate.saviyntcloud.com
        path: /ECM/login/auth
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 60
      periodSeconds: 20
      successThreshold: 1
      timeoutSeconds: 10
    name: ecm
    readinessProbe:
      failureThreshold: 10
      httpGet:
        httpHeaders:
        - name: Host
          value: sji-prod-migrate.saviyntcloud.com
        path: /ECM/login/auth
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 60
      periodSeconds: 20
      successThreshold: 1
      timeoutSeconds: 10
    resources:
      limits:
        cpu: "2"
        memory: 8000Mi
      requests:
        cpu: 700m
        memory: 2000Mi
    startupProbe:
      failureThreshold: 100
      httpGet:
        httpHeaders:
        - name: Host
          value: sji-prod-migrate.saviyntcloud.com
        path: /ECM/login/auth
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 60
      periodSeconds: 20
      successThreshold: 1
      timeoutSeconds: 10
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /tmp/ecm_conf
      name: config-volume
    - mountPath: /tmp/cacerts.bcfks
      name: cert-trust-store
      subPath: cacerts.bcfks
    - mountPath: /usr/local/fips/java.security
      name: ecm-java-security-file
      subPath: ecm.java.security
    - mountPath: /tmp/java.security
      name: java-security-file
      subPath: java.security
    - mountPath: /application_instance
      name: custom-code-repo
    - mountPath: /saviynt_shared
      name: ecm-shared-volume
    - mountPath: /saviynt_shared_certs
      name: shared-certs
    - mountPath: /init/ecm-start.sh
      name: git-sync
      readOnly: true
      subPath: ecm-start.sh
    - mountPath: /prometheus-exporter
      name: prometheus-exporter
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-vnss6
      readOnly: true
  - args:
    - /init/sync-sidecar-start.sh
    command:
    - /bin/sh
    env:
    - name: GIT_REPO
      value: git@gitlab.com:saviynt/cloud-ops/customer-customizations/sji/sji-prod-migrate-eks.git
    - name: GIT_CUSTOM_CODE_DIR
      value: custom_code
    - name: GIT_ROOT_DIR
      value: /application_instance
    image: 661222050851.dkr.ecr.us-east-1.amazonaws.com/alpine-git:master
    imagePullPolicy: IfNotPresent
    name: ecm-sync
    resources:
      limits:
        cpu: 75m
        memory: 250Mi
      requests:
        cpu: 50m
        memory: 100Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /init/sync-sidecar-start.sh
      name: git-sync
      readOnly: true
      subPath: sync-sidecar-start.sh
    - mountPath: /root/.ssh/config
      name: git-sync
      subPath: ssh.config
    - mountPath: /tmp/known_hosts
      name: git-sync
      subPath: known_hosts
    - mountPath: /root/.gitconfig
      name: git-sync
      subPath: .gitconfig
    - mountPath: /application_instance
      name: custom-code-repo
    - mountPath: /root/.ssh/id_rsa
      name: git-key
      subPath: id_rsa
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-vnss6
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: us-west-1-ecr-registry
  - name: us-east-1-ecr-registry
  - name: ap-south-1-ecr-registry
  - name: dockerhub
  - name: gitlab-dependency-proxy
  initContainers:
  - args:
    - -c
    - cp -v /tmp/* /prometheus-exporter/
    command:
    - /bin/sh
    image: 661222050851.dkr.ecr.us-east-1.amazonaws.com/observability-agents:main
    imagePullPolicy: Always
    name: prometheus-exporter
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /prometheus-exporter
      name: prometheus-exporter
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-vnss6
      readOnly: true
  - args:
    - /init/ecm-init-start.sh
    command:
    - /bin/sh
    env:
    - name: GIT_REPO
      value: git@gitlab.com:saviynt/cloud-ops/customer-customizations/sji/sji-prod-migrate-eks.git
    - name: GIT_CUSTOM_CODE_DIR
      value: custom_code
    - name: GIT_ROOT_DIR
      value: /application_instance
    - name: SHARED_BASE_FOLDER
      value: /saviynt_shared
    - name: CYBER_SAFE_TRUST_BROKER_FILE
      value: cstb
    image: 661222050851.dkr.ecr.us-east-1.amazonaws.com/alpine-git:master
    imagePullPolicy: IfNotPresent
    name: ecm-init
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /init/ecm-init-start.sh
      name: git-sync
      readOnly: true
      subPath: ecm-init-start.sh
    - mountPath: /root/.ssh/config
      name: git-sync
      subPath: ssh.config
    - mountPath: /tmp/known_hosts
      name: git-sync
      subPath: known_hosts
    - mountPath: /application_instance
      name: custom-code-repo
    - mountPath: /root/.ssh/id_rsa
      name: git-key
      subPath: id_rsa
    - mountPath: /saviynt_shared
      name: ecm-shared-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-vnss6
      readOnly: true
  nodeName: ip-100-65-102-170.ec2.internal
  preemptionPolicy: PreemptLowerPriority
  priority: 1000000
  priorityClassName: high-priority
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - configMap:
      defaultMode: 420
      name: ecm-config
    name: config-volume
  - configMap:
      defaultMode: 420
      name: git-sync
    name: git-sync
  - configMap:
      defaultMode: 420
      name: cert-trust-store
    name: cert-trust-store
  - configMap:
      defaultMode: 420
      name: cert-trust-store
    name: ecm-java-security-file
  - configMap:
      defaultMode: 420
      name: cert-trust-store
    name: java-security-file
  - configMap:
      defaultMode: 420
      name: cert-trust-store
    name: sso-cert-trust-store
  - emptyDir: {}
    name: custom-code-repo
  - name: ecm-shared-volume
    persistentVolumeClaim:
      claimName: ecm-shared-volume
  - name: shared-certs
    persistentVolumeClaim:
      claimName: shared-certs
  - name: git-key
    secret:
      defaultMode: 384
      items:
      - key: ssh-git-client-private-key
        path: id_rsa
      secretName: ssh-git-client-secret
  - emptyDir: {}
    name: prometheus-exporter
  - name: kube-api-access-vnss6
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-04-29T07:08:18Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-04-29T07:09:38Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-04-29T07:09:38Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-04-29T07:06:14Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://474640d113984b4fdd829e544117454349960a54a59a510ce559ab38e94fdb56
    image: 661222050851.dkr.ecr.us-east-1.amazonaws.com/ecm:Release-24.4.2
    imageID: 661222050851.dkr.ecr.us-east-1.amazonaws.com/ecm@sha256:60c0c8a8272ad924e3b4f0c3f73a7ab70c9e91c887fcd89b23784ec3bce75244
    lastState: {}
    name: ecm
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-04-29T07:08:19Z"
  - containerID: containerd://ffd27787a093f83ee751e06fb92959d3fac4a85021ffa97bc509e4ea75bab682
    image: 661222050851.dkr.ecr.us-east-1.amazonaws.com/alpine-git:master
    imageID: 661222050851.dkr.ecr.us-east-1.amazonaws.com/alpine-git@sha256:4844ee71661a6fe04eed6b1bd77d15ab33f5a83b1296d49c9812325071144909
    lastState: {}
    name: ecm-sync
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-04-29T07:08:19Z"
  hostIP: 100.65.102.170
  initContainerStatuses:
  - containerID: containerd://4e14a1cdb5cd8ac41050fdb8e18bbf3d162ae2ea0a76493842d6157dd59d1372
    image: 661222050851.dkr.ecr.us-east-1.amazonaws.com/observability-agents:main
    imageID: 661222050851.dkr.ecr.us-east-1.amazonaws.com/observability-agents@sha256:ea131b63a45619a353c2b48a8ce361dc92f538b53158792fb77b67233895b626
    lastState: {}
    name: prometheus-exporter
    ready: true
    restartCount: 0
    state:
      terminated:
        containerID: containerd://4e14a1cdb5cd8ac41050fdb8e18bbf3d162ae2ea0a76493842d6157dd59d1372
        exitCode: 0
        finishedAt: "2024-04-29T07:08:16Z"
        reason: Completed
        startedAt: "2024-04-29T07:08:16Z"
  - containerID: containerd://0316fb7d3203ffa0029d296f50720045f3355e81de88cc806b9864eea5d2b9d5
    image: 661222050851.dkr.ecr.us-east-1.amazonaws.com/alpine-git:master
    imageID: 661222050851.dkr.ecr.us-east-1.amazonaws.com/alpine-git@sha256:4844ee71661a6fe04eed6b1bd77d15ab33f5a83b1296d49c9812325071144909
    lastState: {}
    name: ecm-init
    ready: true
    restartCount: 0
    state:
      terminated:
        containerID: containerd://0316fb7d3203ffa0029d296f50720045f3355e81de88cc806b9864eea5d2b9d5
        exitCode: 0
        finishedAt: "2024-04-29T07:08:17Z"
        reason: Completed
        startedAt: "2024-04-29T07:08:17Z"
  phase: Running
  podIP: 100.65.102.167
  podIPs:
  - ip: 100.65.102.167
  qosClass: Burstable
  startTime: "2024-04-29T07:06:14Z"
