apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  azurestack.server: |
    hitachi-powergrids.net:53 { 
           errors
           cache 30 
           forward . 100.64.186.40
           reload 
           }

    blob.core.windows.net:53 { 
           errors
           cache 30 
           forward . 100.64.186.40
           reload 
           }