apiVersion: v1
kind: PersistentVolume
metadata:
 name: pvc-604df6c3-5771-451c-bf11-f11dbbff329d
spec:
 accessModes:
 - ReadWriteOnce
 awsElasticBlockStore:
  fsType: ext4
  volumeID: aws://us-east-1b/vol-014e9d9b9b0bb05b6
 capacity:
  storage: 200
 persistentVolumeReclaimPolicy: Retain
 storageClassName: encrypted-gp2
 volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: data-saviynt-mysql-master-0
spec:
 storageClassName: encrypted-gp2
 accessModes:
  - ReadWriteOnce
 resources:
  requests:
   storage: 200
 volumeMode: Filesystem